### ISSUE TITLE
Pre-processing code for HEP-TH, Cora, and Social Evolution

### ISSUE THREAD

**Issue by danielegrattarola** [VGraphRNN/VGRNN#2]
Hi, 

I've been reading your paper and I wanted to play a bit with the datasets that you used for the experiments. I see that you have uploaded the pre-processed data for Facebook, Enron, and Colab, but I couldn't find the other three datasets. 
Do you have the code to produce the time series for HEP-TH, Cora, and Social Evolution? Or even the pre-processed data like for the other datasets would be good. 

Thanks,
Daniele

**Comment by VGraphRNN** [comment]
Hi,

Sorry for the delayed response. The preprocessing procedure is included in the supplementary materials (http://papers.nips.cc/paper/9254-variational-graph-recurrent-neural-networks-supplemental.zip). We upload other cleaned datasets here soon.

Thanks,
Arman

**Comment by danielegrattarola** [comment]
Thanks!!
